# Generated by Django 5.1.1 on 2024-10-04 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_contributor_book_bookcontributor_book_contributors_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="ibsn",
            new_name="isbn",
        ),
    ]
