# Generated by Django 5.1.1 on 2024-10-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_rename_ibsn_book_isbn"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="book_covers/"),
        ),
        migrations.AddField(
            model_name="book",
            name="sample",
            field=models.FileField(blank=True, null=True, upload_to="book_samples/"),
        ),
    ]
